--- ../tmp/ttf2pt1-3.4.4/Makefile	2002-08-30 20:03:07.000000000 +0200
+++ Makefile	2014-01-09 23:35:28.000000000 +0100
@@ -9,7 +9,7 @@
 #
 # Use GNU C even if it's not the default compiler
 #
-#CC=gcc
+CC=gcc
 #
 # Use the standard ANSI C compiler on HP-UX even if it's not default
 #
@@ -20,11 +20,11 @@
 #
 # Default
 
-CFLAGS_SYS= -O
+#CFLAGS_SYS= -O
 
 # For GNU C
 #
-#CFLAGS_SYS= -O2
+CFLAGS_SYS= -O2
 #
 # For GNU C with long options support library (Linux etc.)
 #
@@ -54,24 +54,24 @@
 # This WON'T BUILD with FT2-beta8, use the FreeType release 2.0.4
 # http://download.sourceforge.net/freetype/freetype-2.0.4.tar.gz
 
-CFLAGS_FT= 
+#CFLAGS_FT= 
 
 # To enable use of the FreeType-2 library
 # (if the include and lib directory do not match your installation,
 # modify them), also uncomment LIBS_FT
 #
-#CFLAGS_FT = -DUSE_FREETYPE -I/usr/local/include/freetype2 -I/usr/local/include
+CFLAGS_FT = -DUSE_FREETYPE -I/usr/include/freetype2/freetype -I/usr/include/freetype2 -I/usr/include
 
 # 
 # The FreeType-2 library flags (disabled by default)
 
-LIBS_FT=
+#LIBS_FT=
 
 # To enable use of the FreeType-2 library
 # (if the include and lib directory do not match your installation,
 # modify them), also uncomment CFLAGS_FT
 #
-#LIBS_FT= -L/usr/local/lib -lfreetype
+LIBS_FT= -L/usr/lib/i386-linux-gnu/ -L/usr/local/lib -lfreetype
 
 #
 # The flags for C compiler for the Autotrace library (disabled by default). 
@@ -104,11 +104,11 @@
 # Preference of front-ends if multiple parsers match a file
 # (by default the build-in front-end takes preference over FreeType)
 
-CFLAGS_PREF=
+#CFLAGS_PREF=
 
 # To prefer FreeType (if enabled):
 #
-#CFLAGS_PREF= -DPREFER_FREETYPE
+CFLAGS_PREF= -DPREFER_FREETYPE
 
 # Uncomment the second line to not compile t1asm into ttf2pt1
 CFLAGS_EXTT1ASM=
@@ -135,11 +135,11 @@
 
 # After you have configured the Makefile, comment out the following
 # definition:
-warning: docs
-	@echo >&2
-	@echo "  You have to configure the Makefile before running make!" >&2
-	@echo "(or if you are lazy and hope that it will work as is run \`make all')">&2
-	@echo >&2
+#warning: docs
+#	@echo >&2
+#	@echo "  You have to configure the Makefile before running make!" >&2
+#	@echo "(or if you are lazy and hope that it will work as is run \`make all')">&2
+#	@echo >&2
 
 DOCS=CHANGES README FONTS FONTS.hpux encodings/README other/README \
 	app/X11/README app/netscape/README app/TeX/README
@@ -244,17 +244,17 @@
 	chmod -R go-w $(SHAREDIR)
 	scripts/inst_file ttf2pt1 $(BINDIR)/ttf2pt1 $(OWNER) $(GROUP) 0755
 	[ -f $(BINDIR)/t1asm ] || scripts/inst_file t1asm $(LIBXDIR)/t1asm $(OWNER) $(GROUP) 0755
-	sed 's|^TTF2PT1_BINDIR=$$|TTF2PT1_BINDIR=$(BINDIR)|;\
-		s|^TTF2PT1_LIBXDIR=$$|TTF2PT1_LIBXDIR=$(LIBXDIR)|;\
-		s|^TTF2PT1_SHAREDIR=$$|TTF2PT1_SHAREDIR=$(SHAREDIR)|;' <scripts/convert >cvt.tmp
+	sed 's|^TTF2PT1_BINDIR=$$|TTF2PT1_BINDIR=$(BINDIR)|;'\
+'		s|^TTF2PT1_LIBXDIR=$$|TTF2PT1_LIBXDIR=$(LIBXDIR)|;'\
+'		s|^TTF2PT1_SHAREDIR=$$|TTF2PT1_SHAREDIR=$(SHAREDIR)|;' <scripts/convert >cvt.tmp
 	scripts/inst_file cvt.tmp $(BINDIR)/ttf2pt1_convert $(OWNER) $(GROUP) 0755
 	scripts/inst_file cvt.tmp $(SHAREDIR)/scripts/convert $(OWNER) $(GROUP) 0755
 	rm cvt.tmp
 	scripts/inst_file scripts/x2gs $(BINDIR)/ttf2pt1_x2gs $(OWNER) $(GROUP) 0755
 	for i in $(MANS1); do { \
-		sed 's|TTF2PT1_BINDIR|$(BINDIR)|;\
-			s|TTF2PT1_LIBXDIR|$(LIBXDIR)|;\
-			s|TTF2PT1_SHAREDIR|$(SHAREDIR)|;' <$$i >$(MANDIR)/man1/$$i \
+		sed 's|TTF2PT1_BINDIR|$(BINDIR)|;'\
+'			s|TTF2PT1_LIBXDIR|$(LIBXDIR)|;'\
+'			s|TTF2PT1_SHAREDIR|$(SHAREDIR)|;' <$$i >$(MANDIR)/man1/$$i \
 		&& chown $(OWNER) $(MANDIR)/man1/$$i \
 		&& chgrp $(GROUP) $(MANDIR)/man1/$$i \
 		&& chmod 0644 $(MANDIR)/man1/$$i \
